version: '3.5'
services:

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5
    ports:
      - 2181:2181
    healthcheck:
      test: "nc -z -v localhost 2181"
      start_period: 10s
  
  mesos-master:
    container_name: mesos-master
    image: mesosphere/mesos-master:1.5.0
    privileged: true
    environment:
      - MESOS_HOSTNAME=$HOST_IP_ADDR
      - MESOS_CLUSTER=SMACK
      - MESOS_QUORUM=1
      - MESOS_ZK=zk://zookeeper:2181/mesos
      - MESOS_LOG_DIR=/tmp/mesos/logs
    links:
      - zookeeper
    ports:
      - 5050:5050
    healthcheck:
      test: "curl -f http://localhost:5050/health || exit 1"
      start_period: 10s

  mesos-slave:
    container_name: mesos-slave
    image: mesosphere/mesos-slave:1.5.0
    privileged: true
    environment:
      - MESOS_HOSTNAME=$HOST_IP_ADDR
      - MESOS_PORT=5151
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_SYSTEMD_ENABLE_SUPPORT=false
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    links:
      - zookeeper
      - mesos-master
    ports:
      - 5151:5151
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    healthcheck:
#      test: ???
#      start_period: 10s

  chronos:
    container_name: chronos
    image: mesosphere/chronos:v3.0.2
    command: '--zk_hosts zookeeper:2181 --master zk://zookeeper:2181/mesos'
    environment:
      PORT0: 4400
      PORT1: 8080
    ports:
      - 4400:4400
    depends_on:
      - zookeeper
      - mesos-master
    links:
      - zookeeper
      - mesos-master
    healthcheck:
      test: "curl -f http://localhost:4400 || exit 1"
      start_period: 10s